spring:
  datasource:
    url: jdbc:h2:mem:dododb
    username: user
    password: pass
  jpa:
    show-sql: true
    # hibernate:
    #   ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
