spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dododb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update